#!/bin/bash -el

echo "Deploying on platform PHP 5.4-1"

APP_DIR=/home/application/current
SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy

/home/application/.venv/bin/python ${SOURCE_DIR}/hooks.py

sudo /home/application/.venv/bin/python ${SOURCE_DIR}/php/apache_modules.py

APP_DIR=/home/application/current
echo ""
echo ""
echo ""
echo "========================================"
echo " Parsing Composer dependances..."
echo ${APP_DIR}
echo "========================================"
echo ""
# check for Composer dependencies and vendors are not bundled in the pack
if [ -f ${APP_DIR}/composer.json ] && [ ! -d ${APP_DIR}/vendor ]; then
    # check if Composer is provided
    if [ -f ${APP_DIR}/composer.phar ]; then
        echo "   Using provided composer..."
    else
        echo "   Downloading composer..."
        wget --quiet http://getcomposer.org/composer.phar -O ${APP_DIR}/composer.phar
    fi

    echo "   Move to ${APP_DIR}..."
    cd ${APP_DIR}
    php ${APP_DIR}/composer.phar install
    cd -
else
    echo "   Missing composer.json file or 'vendor' directory exists. Skipping composer..."
    echo "   pwd"
    pwd
    echo "   ls -la ${APP_DIR}"
    ls -la ${APP_DIR}
fi

# check for application shell config and run it
if [ -f ${APP_DIR}/deploy.sh ]; then
    echo "   Running ${APP_DIR}/deploy.sh ..."
    bash ${APP_DIR}/deploy.sh
fi
